49 w5 2b add automatic deployment of razor page app
ITU-BDSA23-GROUP14/Chirp pull request #56
Opened 2023-10-04 18:05 UTC by jfho

2023-10-04 18:25 UTC, Niklas-ASA approved these changes
Very nice changes, I approve

2023-10-04 19:10 UTC, Mardesol requested changes

2023-10-04 19:24 UTC, jfho commented on src/Chirp.Razor/Chirp.SQLite/DBFacade.cs
> +            //sqlDBFilePath = Path.Combine(Path.GetTempPath(), "chirp.db");
We're assuming we'll go back to having the database in the temporary folder, our current solution is simply a fix while we figure out how to do that properly (likely EmbeddedResource in csproj folder to have everything in one dll file and then something similar to https://stackoverflow.com/questions/34691378/creating-sqlite-database-using-dump-file-programmatically)

2023-10-04 19:25 UTC, jfho commented on test/Chirp.CLI.Client.Tests/UnitTests.cs
We commented out all tests since we felt fixing tests will be done in w5 1.c

2023-10-04 19:33 UTC, Mardesol commented on src/Chirp.Razor/Chirp.SQLite/DBFacade.cs
> +            //sqlDBFilePath = Path.Combine(Path.GetTempPath(), "chirp.db");
Cool, thanks!

2023-10-04 19:34 UTC, Mardesol commented on test/Chirp.CLI.Client.Tests/UnitTests.cs
Great

2023-10-05 09:27 UTC, Mardesol approved these changes
LGTM

2023-10-05 09:29 UTC, merged