61 w6 1b repository pattern
ITU-BDSA23-GROUP14/Chirp pull request #63
Opened 2023-10-05 14:32 UTC by jfho

2023-10-06 11:36 UTC, Mardesol requested changes

2023-10-06 11:36 UTC, Mardesol commented on src/Chirp.Razor/CheepRepository.cs
> +    //public List<CheepViewModel> GetCheeps();
Do we want to keep this around? :)

2023-10-09 12:20 UTC, Niklas-ASA commented on src/Chirp.Razor/CheepRepository.cs
> +    //public List<CheepViewModel> GetCheeps();
I will remove this

2023-10-09 12:35 UTC, Mardesol approved these changes
Good work!

2023-10-09 12:36 UTC, dagruneir approved these changes
look gooood

2023-10-09 12:36 UTC, merged